spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test3
    username: root
    password: root
  liquibase:
    enabled: true
    url: jdbc:mysql://localhost:3306/test3
    user: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
#    generate-ddl: true
    show-sql: true

#  todo ????????????? ???????? ??? user and asana
#  INSERT INTO seq_user(next_val) VALUES (1)


#spring.datasource.url=jdbc:mysql://localhost:3306/test3
#
#spring.datasource.username=root
#spring.datasource.password=root
#
#liquibase.enabled=true
#liquibase.url=jdbc:mysql://localhost:3306/test3
#liquibase.user=root
#liquibase.password=root
#
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.open-in-view=true
 ##spring.jpa.generate-ddl=false
 ##spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#
#server.error.path=/error
#
#hostname=localhost:8080